name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y cmake g++ libvulkan-dev libxinerama-dev libxcursor-dev \
                            libwayland-dev wayland-protocols \
                            libxkbcommon-dev \
                            libxcb1-dev libx11-dev \
                            libgl1-mesa-dev \
                            libxrandr-dev \
                            libxi-dev \
                            libasound2-dev \
                            libpulse-dev \
                            libudev-dev \
                            libdbus-1-dev \
                            libssl-dev \
                            libffi-dev \
                            zlib1g-dev

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensure that submodules are checked out

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
